language: java
sudo: required
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
install: /bin/true
before_install:
  - gradle wrapper
before_script:
  - wget https://services.gradle.org/distributions/gradle-2.14-bin.zip
  - unzip gradle-2.14-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.14
  - export PATH=$GRADLE_HOME/bin:$PATH    
script:
  - ./gradlew assemble
  - ./gradlew build
  - ./gradlew codeCoverageReport
  - ./gradlew jacocoTestReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)